# AMQP client configuration file

# These values will be used to configure the ampq gem, any values
# omitted will let the gem use it's own defaults.

# The configuration specifies the following keys:
# * username - Username for the broker
# * password - Password for the broker
# * host     - Hostname where the broker is running
# * vhost    - Vhost to connect to
# * port     - Port where the broker is running
# * ssl      - Use ssl or not
# * timeout  - Timeout

defaults: &defaults
  username: guest
  password: guest
  host: localhost
  vhost: /

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults